version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data

  backend:
    image: thakorrajp/wanderlust-backend
    container_name: backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    image: thakorrajp/wanderlust-frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

  redis:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    container_name: redis
    expose:
      - 6379
    depends_on:
      - mongodb

volumes:
  data:
