apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crud
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000         # Port inside the cluster
      targetPort: 5000   # Port the pod listens on
      nodePort: 30002 
