apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: crud  # The deployment will be in the 'crud' namespace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: thakorrajp/wanderlust-backend
        ports:
        - containerPort: 5000

