apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: crud
  labels:
    app: frontend
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thakorrajp/wanderlust-frontend
        ports:
        - containerPort: 5173
